### PR TITLE
Update 06_System_Hacking.md

### PR DESCRIPTION
**Pull request by ShubhamPalriwala**
Correction in Subheadings

### CODE REVIEW

**Comment by g0rbe** [comment]
Please check the [TOC](https://danielgorbe.com/en/06_system_hacking/) before modifying the headers.

`Types of Password Attacks` is under `Password Cracking`, not equals. 
`Active Online Attack` is under `Types of Password Attacks`, not equals.

And, please don't include `:` in headers.

**Comment by ShubhamPalriwala** [comment]
Dictionary Attack, Brute Force Attack and Hash Injection come under Active Online attacks.
Wire Sniffing, Man in the Middle attacks come under Passive Online attacks.

So it can be organised in such a way I suppose

**Comment by g0rbe** [comment]
You are right.

But shift `Dictionary Attack`, `Brute Force Attack`, `Hash Injection`, `Wire Sniffing` and `Man in the Middle`  right by one to hold the TOC format.

```
Password Cracking
    Types of password Attacks
        Active online Attacks
            Dictionary Attack
            Brute Force Attack
            Hash Injection
        Passive Online Attacks
            Wire Sniffing
            Man in the Middle
```

**Comment by ShubhamPalriwala** [comment]
The Subheadings are fixed

**Comment by g0rbe** [comment]
Better now :slightly_smiling_face: 
Thanks!

**Pull request merged**
